### ISSUE TITLE
Add a sixth player functionality ?? 

### ISSUE THREAD

**Issue by jbwilkes** [LukasErekson/pyrisk#10]
We could potentially want to allow for a sixth player, but if it's not worth the time then that's fine

(base) Joeys-MBP:pyrisk joeywilkes$ python pyrisk.py -log=$file --deal ChronAI StupidAI*4 BetterAI
Traceback (most recent call last):
  File "pyrisk.py", line 72, in <module>
    curses.wrapper(wrapper, **kwargs)
  File "/Users/joeywilkes/anaconda3/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "pyrisk.py", line 67, in wrapper
    return g.play()
  File "/Users/joeywilkes/senior-labs/402_project/pyrisk/game.py", line 84, in play
    assert 2 <= len(self.players) <= 5
AssertionError

**Comment by lodeous** [comment]
Done in c4dd46df9c0d08436976e5763bd212ecd0650646
