### ISSUE TITLE
New Error ('NoneType' object has no attribute 'getmaxyx')

### ISSUE THREAD

**Issue by jbwilkes** [LukasErekson/pyrisk#11]
This is what I ran - 

`time python pyrisk.py -g=10 SD_StupidAI*2 ChronAI*2 -p=4`

this is an error that was thrown several times

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "pyrisk.py", line 69, in launch_in_process
    victor = wrapper(None, **kwargs)
  File "pyrisk.py", line 18, in wrapper
    g = Game(screen=stdscr, **kwargs)
  File "/acmeshare/jbwilkes/402_projects/pyrisk/game.py", line 43, in __init__
    self.display = CursesDisplay(self.options['screen'], self,
  File "/acmeshare/jbwilkes/402_projects/pyrisk/display.py", line 47, in __init__
    self.sy, self.sx = self.screen.getmaxyx()
AttributeError: 'NoneType' object has no attribute 'getmaxyx'

**Comment by lodeous** [comment]
Ok. The first issue that you are getting is because I didn't properly disable curses with p>1. Running with --nocurses resolves it but I updated the code so curses should now be properly disabled even without --nocurses
