### ISSUE TITLE
Assertion Error w/ AlAI

### ISSUE THREAD

**Issue by jbwilkes** [LukasErekson/pyrisk#9]
This error is thrown in some cases:

'
(base) Joeys-MBP:pyrisk joeywilkes$ time python pyrisk.py -l=$file --deal --nocurses -g=20 AlAI StupidAI

Traceback (most recent call last):
  File "pyrisk.py", line 84, in <module>
    victor = wrapper(None, **kwargs)
  File "pyrisk.py", line 67, in wrapper
    return g.play()
  File "/Users/joeywilkes/senior-labs/402_project/pyrisk/game.py", line 101, in play
    assert sum(choices.values()) == self.player.reinforcements
AssertionError
'

**Comment by jbwilkes** [comment]
note the artificial intelligence is labelled AlAI where second letter is a lowercase L, whereas last letter is capital I (eye - as in ice)
